steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build API
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/smarketing-api:$SHORT_SHA"
      - "."
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    id: Push Backend
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/smarketing-api:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    id: Build DB Migration
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/smarketing-db-migration:$SHORT_SHA"
      - "-f"
      - "DBDockerfile"
      - "."
    dir: "backend"

  - name: "gcr.io/cloud-builders/docker"
    id: Push DB Migration
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/smarketing-db-migration:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    id: Build Client
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/smarketing-client:$SHORT_SHA"
      - "."
    dir: "client"

  - name: "gcr.io/cloud-builders/docker"
    id: Push Client
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/smarketing-client:$SHORT_SHA"

  # Generate the new manifest
  - name: "gcr.io/cloud-builders/gcloud"
    id: Generate manifest
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        sed -i -e "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" k8s/deployment.yaml | \
        sed -i -e 's/BUILD_ID/${SHORT_SHA}/g' k8s/deployment.yaml  | \
        sed -i -e "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/" k8s/db-migration-job.yaml | \
        sed -i -e 's/BUILD_ID/${SHORT_SHA}/g' k8s/db-migration-job.yaml

  - name: "gcr.io/cloud-builders/kubectl"
    id: Deploy
    args:
      - "apply"
      - "-f"
      - "k8s/"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-2"
