version: "3.7"

volumes:
  pgadmin: {}
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: content_planner
    ports:
      - "5432:5432"

  flyway:
    build:
      context: ./migrations
      dockerfile: Dockerfile
    volumes:
      - ./migrations/sql:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/content_planner
      FLYWAY_USER: postgres
    command: migrate
    depends_on: ["postgres"]

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
