version: "3.7"

volumes:
  pgadmin: {}
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: content_planner
    ports:
      - "5432:5432"

  db-migration:
    build:
      context: ./backend
      dockerfile: DBDockerfile
    environment:
      - TYPEORM_HOST=postgres
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=
      - TYPEORM_DATABASE=content_planner
      - TYPEORM_PORT=5432
    depends_on:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
