version: "3.7"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: content_planner
    ports:
      - "5432:5432"
    expose:
      - 5432
