version: "3.7"

volumes:
  pgadmin: {}
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      TYPEORM_HOST: postgres
      TYPEORM_DATABASE: content_planner
      TYPEORM_USERNAME: postgres
      TYPEORM_PORT: 5432
      AUTH0_DOMAIN: https://smarketing.eu.auth0.com/
      AUTH0_AUDIENCE: 4IWpAYFnCEjhtVbxdaXaP0nzVltpmk7A
      FACEBOOK_APP_ID: 2002136040088512
      FACEBOOK_APP_SECRET: 1cc20492fb1361de8bd65cb70a718b40
      TWITTER_CONSUMER_KEY: 0FUfd55TBCepUErv001kUHA89
      TWITTER_CONSUMER_SECRET: pYEmjimbbhDncBGqbxTpFKurcG9SoPzXR8wibKdQOQMZIRwCHC
      FILE_DIR: ./files
    depends_on: ["postgres"]

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: content_planner
    ports:
      - "5432:5432"

  flyway:
    build:
      context: ./migrations
      dockerfile: Dockerfile
    volumes:
      - ./migrations/sql:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/content_planner
      FLYWAY_USER: postgres
    command: migrate
    depends_on: ["postgres"]

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
