apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 60
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: gcr.io/GOOGLE_CLOUD_PROJECT/smarketing-db-migration:BUILD_ID
          env:
            - name: TYPEORM_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: host
            - name: TYPEORM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: TYPEORM_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: TYPEORM_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: port
